with junk_dim_cte as(
SELECT
    ROW_NUMBER() OVER (ORDER BY        automatic_transmission,
    damaged,
    first_owner,
    personal_using,
    turbo,
    alloy_wheels,
    adaptive_cruise_control,
    navigation_system,
    power_liftgate,
    backup_camera,
    keyless_start,
    remote_start,
    sunroof_or_moonroof,
    automatic_emergency_braking,
    stability_control,
    leather_seats,
    memory_seat,
    third_row_seating,
    apple_car_play_or_android_auto,
    bluetooth,
    usb_port,
    heated_seats ) AS junk_id,
    automatic_transmission,
    damaged,
    first_owner,
    personal_using,
    turbo,
    alloy_wheels,
    adaptive_cruise_control,
    navigation_system,
    power_liftgate,
    backup_camera,
    keyless_start,
    remote_start,
    sunroof_or_moonroof,
    automatic_emergency_braking,
    stability_control,
    leather_seats,
    memory_seat,
    third_row_seating,
    apple_car_play_or_android_auto,
    bluetooth,
    usb_port,
    heated_seats
FROM `ready-data-de24.landing_09.cars-com_dataset`
group by automatic_transmission, damaged, first_owner, personal_using, turbo,
                       alloy_wheels, adaptive_cruise_control, navigation_system, power_liftgate,
                       backup_camera, keyless_start, remote_start, sunroof_or_moonroof,
                       automatic_emergency_braking, stability_control, leather_seats,
                       memory_seat, third_row_seating, apple_car_play_or_android_auto,
                       bluetooth, usb_port, heated_seats
)
select junk_id,
        IFNULL(automatic_transmission, -1) AS automatic_transmission,
        IFNULL(damaged, -1) AS damaged,
        IFNULL(first_owner, -1) AS first_owner,
        IFNULL(personal_using, -1) AS personal_using,
        IFNULL(turbo, -1) AS turbo,
        IFNULL(alloy_wheels, -1) AS alloy_wheels,
        IFNULL(adaptive_cruise_control, -1) AS adaptive_cruise_control,
        IFNULL(navigation_system, -1) AS navigation_system,
        IFNULL(power_liftgate, -1) AS power_liftgate,
        IFNULL(backup_camera, -1) AS backup_camera,
        IFNULL(keyless_start, -1) AS keyless_start,
        IFNULL(remote_start, -1) AS remote_start,
        IFNULL(sunroof_or_moonroof, -1) AS sunroof_or_moonroof,
        IFNULL(automatic_emergency_braking, -1) AS automatic_emergency_braking,
        IFNULL(stability_control, -1) AS stability_control,
        IFNULL(leather_seats, -1) AS leather_seats,
        IFNULL(memory_seat, -1) AS memory_seat,
        IFNULL(third_row_seating, -1) AS third_row_seating,
        IFNULL(apple_car_play_or_android_auto, -1) AS apple_car_play_or_android_auto,
        IFNULL(bluetooth, -1) AS bluetooth,
        IFNULL(usb_port, -1) AS usb_port,
        IFNULL(heated_seats, -1) AS heated_seats
from junk_dim_cte
